import test from 'node:test';
import assert from 'node:assert/strict';
import {validateGame,normalizeGame,filterGames,getEligibleGames,pickRandom,addGame,updateGame,deleteGame,collectTags,validState} from '../src/model.js';
import {loadState,saveState,resetState} from '../src/storage.js';
const base={name:'Codenames',minPlayers:4,maxPlayers:8,playMinutes:15,rating:4,tags:'party, Strategy, party',status:'want'};
test('valid game validation and normalization',()=>{assert.deepEqual(validateGame(base),[]);const g=normalizeGame(base,'id1');assert.equal(g.id,'id1');assert.deepEqual(g.tags,['party','strategy']);assert.equal(g.createdAt>0,true)});
test('validation rejects blank name, bad range, rating, and limits',()=>{assert.ok(validateGame({...base,name:' '}).length);assert.ok(validateGame({...base,minPlayers:6,maxPlayers:4}).length);assert.ok(validateGame({...base,rating:6}).length);assert.ok(validateGame({...base,name:'x'.repeat(81)}).length);assert.ok(validateGame({...base,playMinutes:1441}).length);assert.ok(validateGame({...base,tags:'x'.repeat(25)}).length)});
test('CRUD preserves identity and updates timestamp',()=>{const g=normalizeGame(base,'a');let xs=addGame([],g);xs=updateGame(xs,'a',{name:'New'});assert.equal(xs[0].name,'New');assert.equal(xs[0].id,'a');assert.equal(xs[0].createdAt,g.createdAt);assert.equal(deleteGame(xs,'a').length,0)});
test('combined search, tag, status filtering and tag collection',()=>{const a=normalizeGame(base,'a'),b=normalizeGame({...base,name:'Azul',tags:'strategy',status:'played'},'b');assert.deepEqual(filterGames([a,b],{query:'code',tag:'party',status:'want'}).map(x=>x.id),['a']);assert.deepEqual(filterGames([a,b],{status:'played'}).map(x=>x.id),['b']);assert.deepEqual(collectTags([a,b]),['party','strategy'])});
test('picker excludes played and incompatible games and supports deterministic rng',()=>{const a=normalizeGame(base,'a'),b=normalizeGame({...base,name:'x',minPlayers:1,maxPlayers:2},'b'),c=normalizeGame({...base,name:'y',status:'played'},'c');assert.deepEqual(getEligibleGames([a,b,c],4).map(x=>x.id),['a']);assert.equal(pickRandom([a,b,c],4,()=>0).id,'a');assert.equal(pickRandom([b],4,()=>0),null);assert.equal(pickRandom([a],0),null)});
test('malformed JSON and invalid schema are recoverable',()=>{assert.equal(loadState({getItem:()=>'{bad'}).ok,false);assert.equal(loadState({getItem:()=>JSON.stringify({version:1,games:[{id:'x'}]})}).ok,false);assert.equal(validState({version:1,games:[]}),true)});
test('save/load round trip and reset work',()=>{const m={data:null,getItem(){return this.data},setItem(k,v){this.data=v},removeItem(){this.data=null}};assert.equal(saveState(m,{games:[]}).ok,true);assert.deepEqual(loadState(m).games,[]);assert.equal(resetState(m).ok,true);assert.equal(loadState(m).games.length,0)});
test('storage write failure is visible',()=>{const m={setItem(){throw Error('quota')}};assert.equal(saveState(m,{games:[]}).ok,false)});
// Required browser-flow logic remains pure and directly tested through the model API.
