import {validateGame,normalizeGame,addGame,updateGame,deleteGame,filterGames,getEligibleGames,pickRandom,collectTags,emptyState} from './model.js';import {loadState,saveState,resetState} from './storage.js';import { $,renderGames,formData,text,showEmpty,pickerResult } from './view.js';
const storage=(()=>{try{return globalThis.localStorage}catch(e){return {getItem(){throw e},setItem(){throw e},removeItem(){throw e}}}})();let state=loadState(storage),editing=null,pending=null;const form=$('#game-form');
function uniqueId(games){let id;do{id=globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`}while(games.some(g=>g.id===id));return id}
function persist(){const r=saveState(storage,state);$('#storage').textContent=r.ok?'Saved locally.':r.error}
function recover(){const r=resetState(storage);if(r.ok){state={ok:true,...emptyState()};$('#storage').textContent='Collection reset. You can start fresh.';render()}else $('#storage').textContent=r.error}
function showErrors(errors){for(const id of ['name','minPlayers','maxPlayers','playMinutes','rating','tags'])$('#'+id+'-error').textContent='';for(const error of errors){const id=error.startsWith('Name')?'name':error.startsWith('Minimum')?'minPlayers':error.startsWith('Maximum')?'maxPlayers':error.startsWith('Play time')?'playMinutes':error.startsWith('Rating')?'rating':error.startsWith('Tags')?'tags':'';if(id)$('#'+id+'-error').textContent=error}$('#form-error').textContent=errors.length?'Please correct the highlighted fields.':''}
function startAdd(){editing=null;form.reset();$('#form-title').textContent='Add a game';showErrors([]);form.elements.name.focus()}
function render(){const games=Array.isArray(state.games)?state.games:[],fs={query:$('#search').value,tag:$('#tag').value,status:$('#status').value},shown=filterGames(games,fs);$('#stats').textContent=`${games.length} games · ${games.filter(x=>x.status==='want').length} wanted`;
$('#count').textContent=`${shown.length} shown`;renderGames($('#games'),shown,action);if(!games.length)showEmpty($('#empty'),startAdd);else if(!shown.length)$('#empty').replaceChildren(text('span','No games match. '),text('button','Clear filters'));else $('#empty').replaceChildren();const clear=$('#empty button');if(clear)clear.onclick=()=>$('#clear').click();const tags=collectTags(games),sel=$('#tag'),old=sel.value;sel.replaceChildren(text('option','All tags'));sel.firstChild.value='all';tags.forEach(t=>{const o=text('option',t);o.value=t;sel.append(o)});sel.value=tags.includes(old)?old:'all';const n=+$('#players').value,a=getEligibleGames(games,n);$('#eligible').textContent=`${a.length} eligible game${a.length===1?'':'s'}`;if(!state.ok){$('#storage').replaceChildren(text('span',state.error),text('button','Reset local collection'));const reset=$('#storage button');reset.type='button';reset.onclick=recover;const retry=text('button','Retry reload');retry.type='button';retry.onclick=()=>location.reload();$('#storage').append(retry)}}
function action(type,g){if(type==='edit'){editing=g;$('#form-title').textContent='Edit game';for(const [k,v] of Object.entries(g))if(form.elements[k])form.elements[k].value=Array.isArray(v)?v.join(', '):v;form.elements.name.focus();return}if(type==='status'){state.games=updateGame(state.games,g.id,{status:g.status==='want'?'played':'want'});persist();render();return}pending=g;$('#confirm-text').textContent=`Delete ${g.name}?`;$('#confirm').showModal()}
form.onsubmit=e=>{e.preventDefault();const d=formData(form),errors=validateGame(d);showErrors(errors);if(errors.length)return;const g=normalizeGame(d,editing?.id||uniqueId(state.games));state.games=editing?updateGame(state.games,g.id,g):addGame(state.games,g);editing=null;form.reset();$('#form-title').textContent='Add a game';showErrors([]);persist();render()};$('#cancel').onclick=startAdd;$('#yes').onclick=()=>{if(pending){state.games=deleteGame(state.games,pending.id);pending=null}$('#confirm').close();persist();render()};$('#no').onclick=()=>{$('#confirm').close();pending=null};$('#clear').onclick=()=>{$('#search').value='';$('#status').value='all';$('#tag').value='all';render()};['search','status','tag','players'].forEach(id=>$('#'+id).oninput=render);$('#pick').onclick=()=>pickerResult($('#result'),pickRandom(Array.isArray(state.games)?state.games:[],+$('#players').value));render();
